CREATE TABLE Producteur (NoProducteur INTEGER PRIMARY KEY AUTOINCREMENT, Nom VARCHAR(40) NOT NULL , Prenom VARCHAR(40) NOT NULL, Ville VARCHAR(30));
CREATE TABLE Produit (NoProduit INTEGER PRIMARY KEY AUTOINCREMENT,Nom VARCHAR(30) NOT NULL, NoProducteur INTEGER NOT NULL, "PrixKilo" FLOAT, "Bio" BOOL,
CONSTRAINT fk_NoProducteur FOREIGN KEY (NoProducteur) REFERENCES Producteur (NoProducteur) ON DELETE CASCADE ON UPDATE CASCADE);
